In [1]:
import numpy as np
import random
from time import sleep

def create_board():
    return np.zeros((3, 3), dtype=int)

def possibilities(board):
    """Returns a list of empty positions on the board."""
    return [(i, j) for i in range(3) for j in range(3) if board[i, j] == 0]

def random_place(board, player):
    """Randomly places a move for the player if there are available moves."""
    selection = possibilities(board)
    if selection:
        current_loc = random.choice(selection)
        board[current_loc[0], current_loc[1]] = player
    return board

def check_win(board, player):
    """Checks if the given player has won the game."""
    return (
        np.any(np.all(board == player, axis=0)) or  # Check columns
        np.any(np.all(board == player, axis=1)) or  # Check rows
        np.all(np.diag(board) == player) or         # Check main diagonal
        np.all(np.diag(np.fliplr(board)) == player) # Check secondary diagonal
    )

def evaluate(board):
    """Evaluates the board state and returns the winner if there is one."""
    for player in [1, 2]:
        if check_win(board, player):
            return player  # Return the winning player (1 or 2)
    return -1 if np.all(board != 0) else 0  # Return -1 if it's a draw, 0 if still in progress

def play_game():
    """Plays a complete game and returns the winner."""
    board = create_board()
    winner = 0
    counter = 1
    
    print("Starting Board:\n", board)
    sleep(1)

    while winner == 0:
        for player in [1, 2]:
            board = random_place(board, player)
            print(f"\nBoard after move {counter} by Player {player}:\n", board)
            sleep(1)
            counter += 1
            winner = evaluate(board)
            if winner != 0:
                break  # End game if there is a winner

    print("\nFinal Board:\n", board)
    return f"Winner is: Player {winner}" if winner > 0 else "It's a Draw!"

# Driver Code
print(play_game())


Starting Board:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Board after move 1 by Player 1:
 [[0 0 0]
 [0 1 0]
 [0 0 0]]

Board after move 2 by Player 2:
 [[0 0 0]
 [0 1 0]
 [0 0 2]]

Board after move 3 by Player 1:
 [[0 0 0]
 [0 1 1]
 [0 0 2]]

Board after move 4 by Player 2:
 [[2 0 0]
 [0 1 1]
 [0 0 2]]

Board after move 5 by Player 1:
 [[2 0 0]
 [1 1 1]
 [0 0 2]]

Final Board:
 [[2 0 0]
 [1 1 1]
 [0 0 2]]
Winner is: Player 1
